version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres-vectorstore
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: conversation_store
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: chatbot_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatbot_user -d conversation_store"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
    driver: local
